import streamlit as st
import asyncio
from agents import Runner
from agent_factory import build_agents
import pandas as pd
import logging

# Configure standard terminal logging directly for the Streamlit runner
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(message)s",
    datefmt="%H:%M:%S"
)
logger = logging.getLogger("streamlit_app")

# Example tracking statement inside your file initialization
logger.info("Streamlit server application wrapper booted successfully.")

# 1. Page Configuration
st.set_page_config(page_title="AI Breakfast Planner", page_icon="🍳", layout="centered")

st.title("🍳 The Ultimate AI Breakfast Planner")
st.write("Powered by GitHub Models, ChromaDB, and Exa Search.")

# 2. Cache the Agents! 
# (This ensures we don't rebuild the agents every time you click a button)
@st.cache_resource
def load_ai_system():
    # Make sure your .env is loaded here if you moved load_dotenv() out of config!
    from dotenv import load_dotenv
    load_dotenv()
    
    return build_agents()

agents = load_ai_system()
advisor_agent = agents["breakfast_advisor"]

# 3. Create the User Interface
user_input = st.text_area(
    "What kind of breakfast are you looking for?", 
    value="I need a high-protein, quick breakfast for busy mornings."
)

# 4. The Action Button
if st.button("Generate Breakfast Plan", type="primary"):
    
    # Show a loading spinner while the agents are thinking
    with st.spinner("Chefs are preparing your plan, searching calories, and checking prices..."):
        try:
            # Run the async agent loop inside Streamlit's sync environment
            result = asyncio.run(Runner.run(advisor_agent, user_input))
            structured_data = result.final_output

            # Display the result beautifully using Markdown!
            st.success("Plan Complete!")
            st.markdown("---")
            st.markdown(result.final_output)
            st.markdown("### 📝 Recommended Menu")
            st.markdown(structured_data.text_response)
            
            st.markdown("---")
            st.markdown("### 📊 Calorie Comparison Matrix")
            
            # 3. Convert the Pydantic data list into a Pandas DataFrame
            raw_chart_items = [
                {"Meal": item.food_item, "Calories (kcal)": item.calories} 
                for item in structured_data.chart_data
            ]
            
            if raw_chart_items:
                df = pd.DataFrame(raw_chart_items)
                
                # 4. Sort the DataFrame by calories for a clean visualization
                df = df.sort_values(by="Calories (kcal)", ascending=False)
                
                # 5. Set the index to the meal names so Streamlit labels the axes properly
                df = df.set_index("Meal")
                
                # 6. Render the interactive chart!
                st.bar_chart(df, y="Calories (kcal)", color="#FF4B4B")
            else:
                st.warning("No chart data was generated by the agent.")
            
        except Exception as e:
            st.error(f"Oh no! The kitchen caught on fire: {e}")

st.markdown("---")
st.caption("Check your [LangSmith Dashboard](https://smith.langchain.com/) to see the background agent traces!")