import streamlit as st
import asyncio
from agents import Runner
from agent_factory import build_agents
import pandas as pd
import logging

# Configure standard terminal logging directly for the Streamlit runner
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(message)s",
    datefmt="%H:%M:%S"
)
logger = logging.getLogger("streamlit_app")
logger.info("Streamlit server application wrapper booted successfully.")

# 1. Page Configuration
st.set_page_config(page_title="AI Breakfast Planner", page_icon="🍳", layout="centered")

st.title("🍳 The Ultimate AI Breakfast Planner")
st.write("Powered by GitHub Models, ChromaDB, and Exa Search.")

# --- NEW: Initialize Persistent Session Storage ---
# This keeps your generated plans on the screen even if you click other buttons
if "current_response" not in st.session_state:
    st.session_state.current_response = None
if "previous_response" not in st.session_state:
    st.session_state.previous_response = None

# 2. Cache the Agents!
@st.cache_resource
def load_ai_system():
    from dotenv import load_dotenv
    load_dotenv()
    return build_agents()

agents = load_ai_system()
advisor_agent = agents["breakfast_advisor"]

# 3. Create the User Interface
user_input = st.text_area(
    "What kind of breakfast are you looking for?", 
    value="I need a high-protein, quick breakfast for busy mornings."
)

# --- NEW: Button Layout ---
col1, col2 = st.columns(2)
with col1:
    generate_clicked = st.button("Generate Breakfast Plan", type="primary", use_container_width=True)
with col2:
    show_prev_clicked = st.button(
        "Show Previous Response", 
        type="secondary", 
        disabled=(st.session_state.previous_response is None),
        use_container_width=True
    )

# --- NEW: Helper Function to Render Data ---
def render_plan_data(structured_data):
    """Parses the Pydantic JSON and draws the UI components."""
    
    st.success("Plan Complete!")
    
    # 1. Check for the Slides URL and draw a big button!
    # Using getattr is a safe way to check if the AI successfully included the link
    slides_url = getattr(structured_data, 'slides_url', None)
    if slides_url:
        st.link_button("📊 Open Google Slides Deck", slides_url, type="primary", use_container_width=True)
        st.markdown("---")

    # 2. Draw the Text
    st.markdown("### 📝 Recommended Menu")
    st.markdown(structured_data.text_response)
    
    st.markdown("---")
    st.markdown("### 📊 Calorie Comparison Matrix")
    
    # 3. Draw the Chart
    raw_chart_items = [
        {"Meal": item.food_item, "Calories (kcal)": item.calories} 
        for item in structured_data.chart_data
    ]
    
    if raw_chart_items:
        df = pd.DataFrame(raw_chart_items)
        df = df.sort_values(by="Calories (kcal)", ascending=False)
        df = df.set_index("Meal")
        st.bar_chart(df, y="Calories (kcal)", color="#FF4B4B")
    else:
        st.warning("No chart data was generated by the agent.")


# 4. Action Logic: Generating a New Plan
if generate_clicked:
    with st.spinner("Chefs are preparing your plan, building slides, and checking prices..."):
        try:
            # Run the agent
            result = asyncio.run(Runner.run(advisor_agent, user_input))
            
            # Shift old plan to previous memory
            if st.session_state.current_response is not None:
                st.session_state.previous_response = st.session_state.current_response
                
            # Save new plan to current memory
            st.session_state.current_response = result.final_output
            
            # Render it!
            render_plan_data(st.session_state.current_response)
            
        except Exception as e:
            st.error(f"Oh no! The kitchen caught on fire: {e}")

# Action Logic: Showing Previous Plan
elif show_prev_clicked:
    if st.session_state.previous_response is not None:
        st.info("⏮️ Showing data from your previous generated response:")
        render_plan_data(st.session_state.previous_response)

# Action Logic: Keep Current Plan Visible 
elif st.session_state.current_response is not None:
    render_plan_data(st.session_state.current_response)

st.markdown("---")
st.caption("Check your [LangSmith Dashboard](https://smith.langchain.com/) to see the background agent traces!")